import { type WriteStatements } from '../types';

/////////////////////////////////////////////////
// FUNCTION
/////////////////////////////////////////////////

export const writeSingleFileHeading: WriteStatements = ({ writer }) => {
  writer.writeLine(
    '/* !!! This is code generated by zod-prisma-schema. Do not edit directly. !!! */',
  );
  writer.blankLine();
  writer.writeLine('/* eslint-disable */');
  writer.blankLine();
  writer.writeLine('// @ts-nocheck');
  writer.blankLine();
};
